apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: quarkus-runner-deployment-gitops-repository
spec:
  url: https://github.com/lucarval-rhtap/quarkus-runner-deployment-gitops