apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: quarkus-runner-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/lucarval-rhtap/quarkus-runner-deployment:github-9a183a223bbfcba4da5ea8e0855b4830d22379a8
          name: container-image
